version: 2

models:
  - name: stg_greenery__addresses
    description: Fact table - location (delivery) information associated with greenery's users (GDPR)

  - name: stg_greenery__events
    description: Fact table - greenery's users site sessions and events
  
  - name: stg_greenery__orders
    description: Fact table - greenery's orders, deliveries and shipping
    columns:
      - name: order_id
        tests:
        - not_null
        - unique

  - name: stg_greenery__order_items
    description: Fact table - items per order (including quantity) 
  
  - name: stg_greenery__products
    description: Dimension table - greenery's products and inventory

  - name: stg_greenery__promos
    description: Dimension table - greenery's promotions
  
  - name: stg_greenery__users
    description: Dimension table - demographic information and contact details for greenery's users (GDPR)
    columns:
      - name: user_id
        tests:
        - not_null
        - unique
