version: 2

models:
  - name: stg_greenery__addresses
    description: Contains delivery location information associated with greenery's users (GDPR)

  - name: stg_greenery__events
    description: Contains information regarding greenery's users site events 
  
  - name: stg_greenery__order_items
    description: Contains information regarding orders, deliveries and shipping 
  
  - name: stg_greenery__orders
    description: Contains list of items per order 
    columns:
      - name: order_id
        tests:
        - not_null
        - unique

  - name: stg_greenery__products
    description: Contains information regarding greenery's products
  
  - name: stg_greenery__promos
    description: Contains information regarding greenery's promotions
  
  - name: stg_greenery__users
    description: Contains demographic information and contact details for greenery's users (GDPR)
    columns:
      - name: user_id
        tests:
        - not_null
        - unique
