version: 2

exposures:  
  - name: Product Funnel Dashboard
    description: >
      Models that are critical to our product funnel dashboard
    type: dashboard
    maturity: high
    owner:
      name: Matilda Hultgren
      email: matilda@greenery.com
    depends_on:
      - ref('fct_product_events')